### PR TITLE
Added CONTRIBUTION.md, changed code style to PEP8, docstring style to…

### PR DESCRIPTION
**Pull request by Prayag2**
### Changes
- Changed code style to [PEP8](https://www.python.org/dev/peps/pep-0008/)
- Changed docstring style to [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html)

## Additions
- Added a CONTRIBUTION.md

## Fixes
- Fixed a possible bug. Refer to [#26](https://github.com/Prayag2/konsave/issues/26).

### CODE REVIEW

**Comment by Prayag2** [comment]
There was no response so I'm merging it :(

**Comment by majabojarska** [comment]
Hi @Prayag2, I declared that I would look at the projects on the weekends. You requested me as a reviewer. I would look into the changes right now, but don't expect responses from me on workdays.

About the changes:

- Python compiled (`*.pyc`) files are temporary files generated by the interpreter. Those shouldn't be added nor tracked by version control systems. Not sure how they got commited, since those are gitignored (force add?). I'll revert this today.
- `CONTRIBUTION.md` looks great.
- Minor stuff like missing newline at end of file, but I'll handle that.

**Comment by Prayag2** [comment]
Oh, I'm sorry! I forgot that you are busy on workdays. 
> Python compiled (*.pyc) files are temporary files generated by the interpreter. Those shouldn't be added nor tracked by version control systems. Not sure how they got commited, since those are gitignored (force add?). I'll revert this today.
  
I was thinking about this too! I don't know why but the `__pycache__` folder is getting tracked too.

> Minor stuff like missing newline at end of file, but I'll handle that.
  
okay thanks!

**Comment by majabojarska** [comment]
> I was thinking about this too! I don't know why but the __pycache__ folder is getting tracked too.
Probably was added some time ago and wasn't removed from Git history. Fixed this in #30 :wink:.

**Pull request merged**
