### PR TITLE
Create changelog

### PR DESCRIPTION
**Pull request by majabojarska**
This PR adds a `CHANGELOG.md` file for tracking changes in an organized way. The changelog assumes that [SemVer](https://semver.org/) is used for versioning releases. The changelog adheres to the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

### CODE REVIEW

**Comment by majabojarska** [comment]
I created a header (H2) and diff link for each release. Not filling them out, as it's tricky to figure out the changes just from the git logs. However, it would be good to start logging the changes from now on.

**Comment by Prayag2** [comment]
Thank you so much! Your help is greatly appreciated!

**Comment by Prayag2** [comment]
I wanted to ask something because I'm still a student and quite new to open source and stuff. I am pushing commits literally everyday and sometimes I mess up. So, should I make another branch like a "stable" branch where I would only push commits once I find them stable enough? Thank you!

**Comment by majabojarska** [comment]
I'll respond to your question via private email, so we don't go off-topic in this PR :wink:.

**Pull request merged**
