### PR TITLE
Printing out version should not be dependent on DE

### PR DESCRIPTION
**Pull request by mmahmoudian**
The following shows that the code checks if the config file exists before parse the arguments, but showing version should be independent of that.
image

### CODE REVIEW

**Comment by Prayag2** [comment]
It doesn't depend on the DE. Konsave prompts you to enter your DE only when launching it for the first time. It will ask you for your DE only for the first time.

**Comment by mmahmoudian** [comment]
The issue is that when user asks for version, no other process should be done, even checking the DE and checking if the config file exists or not. I understand that the code doesn't look as neat as before, but this is what it takes to fix that issue.

**Comment by Prayag2** [comment]
Maybe I can print something like "This is only a one time setup"

**Comment by mmahmoudian** [comment]
That's visually better, I agree. Although it doesn't address the extra and unnecessary code being run.

But considering they type of software this is and the very small footprint, I think your solution works.

**Comment by Prayag2** [comment]
And also this will only run when launching Konsave for the first time so it isn't much of an issue. Thanks :D

**Pull request closed without merging**
