### PR TITLE
docs: style `README`

### PR DESCRIPTION
**Pull request by scarf005**
- style: remove trailing whitespace
- style: use `---` over `<hr>`
- style: syntax highlight code block

### CODE REVIEW

**Comment by Prayag2** [comment]
The trailing whitespaces are there for a reason! Trailing whitespaces, in markdown, are used to start a new line. 

**This is before removing trailing whitespaces-**
image

**This is after removing trailing whitespaces-**
image

**Comment by scarf005** [comment]
I see, I didn't know that trailing whitespaces work as line break. however the PR doesn't end here! there's also 91605436e2f915bf2b4ce668c48af91476821104 and 3bbb78ce32120af7dec01a380227e182360f028a

**Comment by Prayag2** [comment]
Okay. I'll merge it but please remove [this](https://github.com/Prayag2/konsave/pull/73/commits/f0d9ae0354350d5e6abc508dd4a021fbe9c65509) commit.

**Comment by scarf005** [comment]
alright, removed the commit.

**Pull request closed without merging**
